
INSERT INTO SALE_ORDER (ID, WAREHOUSE_ID, MTRL_RESPONSIBLE_ID, DELIVERY, TAX_DELIVERY, DELIVERY_WITH_TAX, CURRENCY_DELIVERY, CURRENCY_TAX_DELIVERY, CURRENCY_DELIVERY_WITH_TAX) VALUES (4, 200, 600, 0, 0, 0, 0, 0, 0);
INSERT INTO SALE_ORDER (ID, WAREHOUSE_ID, MTRL_RESPONSIBLE_ID, DELIVERY, TAX_DELIVERY, DELIVERY_WITH_TAX, CURRENCY_DELIVERY, CURRENCY_TAX_DELIVERY, CURRENCY_DELIVERY_WITH_TAX) VALUES (5, 200, 600, 0, 0, 0, 0, 0, 0);
INSERT INTO SALE_ORDER (ID, WAREHOUSE_ID, MTRL_RESPONSIBLE_ID, DELIVERY, TAX_DELIVERY, DELIVERY_WITH_TAX, CURRENCY_DELIVERY, CURRENCY_TAX_DELIVERY, CURRENCY_DELIVERY_WITH_TAX) VALUES (6, 201, 601, 0, 0, 0, 0, 0, 0);
INSERT INTO SALE_ORDER (ID, WAREHOUSE_ID, MTRL_RESPONSIBLE_ID, DELIVERY, TAX_DELIVERY, DELIVERY_WITH_TAX, CURRENCY_DELIVERY, CURRENCY_TAX_DELIVERY, CURRENCY_DELIVERY_WITH_TAX) VALUES (10, 200, 600, 0, 0, 0, 0, 0, 0);


