
CREATE VIEW V_RPT_GOODS_ROTATE (
 ORGANIZATION_ID,
 PERIOD_ID, 
 PRODUCT_ID, 
 REST_QUANTITY,
 REST_AMOUNT, 
 CREDIT_QUANTITY,
 CREDIT_AMOUNT,
 DEBIT_QUANTITY,
 DEBIT_AMOUNT
) AS
SELECT R.ORGANIZATION_ID, R.PERIOD_ID, 
 R.PRODUCT_ID,
 CAST(R.QUANTITY AS NUMERIC(9, 4)) AS REST_QUANTITY, CAST(R.AMOUNT AS NUMERIC(9,2)) AS REST_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 4)) AS CREDIT_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS CREDIT_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 4)) AS DEBIT_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS DEBIT_AMOUNT
 FROM V_RPT_GOODS_REST_START R
UNION ALL 
SELECT D.ORGANIZATION_ID, D.PERIOD_ID, 
 D.PRODUCT_ID, CAST(0.0 AS NUMERIC(9, 4)) AS REST_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS REST_AMOUNT,
 CAST(D.QUANTITY AS NUMERIC(9, 4)) AS CREDIT_QUANTITY, CAST(D.AMOUNT AS NUMERIC(9,2)) AS CREDIT_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 4)) AS DEBIT_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS DEBIT_AMOUNT
 FROM V_GOODS_CREDIT_FULL D
UNION ALL 
SELECT C.ORGANIZATION_ID, C.PERIOD_ID, 
 C.PRODUCT_ID, CAST(0.0 AS NUMERIC(9, 4)) AS REST_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS REST_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 4)) AS CREDIT_QUANTITY, CAST(0.0 AS NUMERIC(9, 2)) AS CREDIT_AMOUNT,
 CAST(C.QUANTITY AS NUMERIC(9, 4)) AS DEBIT_QUANTITY, CAST(C.AMOUNT AS NUMERIC(9,2)) AS DEBIT_AMOUNT
 FROM V_GOODS_DEBIT_FULL C;
