engines:
  structure:
    enabled: false
  duplication:
    enabled: false
  sonar-java:
    enabled: true
    channel: beta
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**/*.png"
  - "**/*.gif"
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
