

INSERT INTO PAYMENT_INCOME (ID, ORGANIZATION_BANK_ACCOUNT_ID, PARTNER_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, SEND_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (30, 1, 2, 1, 1, '2011-01-06', NULL, 'за товар', NULL);
INSERT INTO PAYMENT_INCOME (ID, ORGANIZATION_BANK_ACCOUNT_ID, PARTNER_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, SEND_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (31, 1, 3, 1, 1, '2011-01-06', NULL, 'за товар', NULL);
INSERT INTO PAYMENT_INCOME (ID, ORGANIZATION_BANK_ACCOUNT_ID, PARTNER_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, SEND_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (32, 1, 3, 1, 1, '2011-02-07', NULL, 'за товар', NULL);
INSERT INTO PAYMENT_INCOME (ID, ORGANIZATION_BANK_ACCOUNT_ID, PARTNER_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, SEND_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (33, 1, 4, 1, 1, '2011-01-09', NULL, 'за товар', NULL);


