
INSERT INTO JOB_POSITION (ID, CODE, NAME) VALUES (1, '1', 'Specialist');
INSERT INTO JOB_POSITION (ID, CODE, NAME) VALUES (2, '2', 'Manager');
INSERT INTO JOB_POSITION (ID, CODE, NAME) VALUES (3, '3', 'Executive');
INSERT INTO JOB_POSITION (ID, CODE, NAME) VALUES (4, '4', 'Head of department');
INSERT INTO JOB_POSITION (ID, CODE, NAME) VALUES (5, '5', 'Second person');