
/* ------------------------------------------------------------------------------------------------------------ */
/* GENERAL INITIALIZATION                                                                                       */
/* ------------------------------------------------------------------------------------------------------------ */

INSERT INTO SYS_ROLE (ID, NAME) VALUES (1, 'SUPERVISOR');
INSERT INTO SYS_USER (ID, USER_NAME, USER_PASSWORD, NAME, REG_DATE) VALUES (1, 'admin', '098f6bcd4621d373cade4e832627b4f6', 'Администратор', '2011-01-01');
INSERT INTO SYS_USER_ROLE (ID, USER_ID, ROLE_ID) VALUES (1, 1, 1);


INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (1,'ACADEMIC_DEGREE','ACADEMIC_DEGREE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (2,'ACTIVITY_TYPE','ACTIVITY_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (3,'ADDRESS_TYPE','ADDRESS_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (4,'APARTMENT_TYPE','APARTMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (5,'BANK','BANK','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (6,'CASH_INCOME','CASH_INCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (7,'CASH_OUTCOME','CASH_OUTCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (8,'CITY','CITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (9,'CONTACT','CONTACT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (10,'CONTACT_TYPE','CONTACT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (11,'CONTRACT','CONTRACT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (12,'CONTRACTOR','CONTRACTOR','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (13,'COUNTRY','COUNTRY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (14,'CURRENCY','CURRENCY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (15,'DEPARTMENT','DEPARTMENT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (16,'DISCHARGE_TYPE','DISCHARGE_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (17,'DISTRICT','DISTRICT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (18,'DOCUMENT_TYPE','DOCUMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (19,'EDUCATION_FORM','EDUCATION_FORM','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (20,'EDUCATION_INSTITUTE','EDUCATION_INSTITUTE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (21,'EDUCATION_TYPE','EDUCATION_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (22,'EMPLOYEE','EMPLOYEE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (23,'EMPLOYEE_CATEGORY','EMPLOYEE_CATEGORY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (24,'EMPLOYEE_DISCHARGE','EMPLOYEE_DISCHARGE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (25,'EMPLOYEE_VACATION','EMPLOYEE_VACATION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (26,'EMPLOYEE_RANK','EMPLOYEE_RANK','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (27,'EMPLOYEE_RECEPTION','EMPLOYEE_RECEPTION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (28,'EMPLOYEE_SICKLIST','EMPLOYEE_SICKLIST','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (29,'SALE_SERV','SALE_SERV','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (30,'FAMILIARITY','FAMILIARITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (31,'FAMILY_STATUS','FAMILY_STATUS','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (32,'FINANCE_DOCUMENT_TYPE','FINANCE_DOCUMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (33,'FORM_PROPERTY','FORM_PROPERTY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (34,'GOODS','GOODS','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (35,'GOODS_INCOME','GOODS_INCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (36,'INVENTORY_MOVE','INVENTORY_MOVE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (37,'GOODS_OUTCOME','GOODS_OUTCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (38,'INVENTORY_REST','INVENTORY_REST','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (39,'GOODS_TYPE','GOODS_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (40,'INVENTORY_WRITEOFF','INVENTORY_WRITEOFF','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (41,'INDUSTRY','INDUSTRY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (42,'SALE_INVOICE','SALE_INVOICE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (43,'LANGUAGE','LANGUAGE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (44,'VACATION_AVERANGE_TYPE','VACATION_AVERANGE_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (45,'VACATION_CALCULATE','VACATION_CALCULATE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (46,'VACATION_TYPE','VACATION_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (47,'LEDGER_ACCOUNT','LEDGER_ACCOUNT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (48,'LEDGER_ACCOUNT_REST','LEDGER_ACCOUNT_REST','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (49,'LEDGER_ACCOUNT_TYPE','LEDGER_ACCOUNT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (50,'LOCALITY','LOCALITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (51,'LOCALITY_TYPE','LOCALITY_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (52,'MILITARY_RANK','MILITARY_RANK','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (53,'MILITARY_SPECIALITY','MILITARY_SPECIALITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (54,'MILITARY_STATUS','MILITARY_STATUS','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (55,'ORGANIZATION','ORGANIZATION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (56,'PARTNER','PARTNER','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (57,'PARTNER_CATEGORY','PARTNER_CATEGORY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (58,'PARTNER_GROUP','PARTNER_GROUP','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (59,'PARTNER_REST','PARTNER_REST','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (60,'PAYMENT_INCOME','PAYMENT_INCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (61,'PAYMENT_OUTCOME','PAYMENT_OUTCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (62,'PAYMENT_TYPE','PAYMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (63,'PAYROLL','PAYROLL','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (64,'PAYROLL_ALGORITM','PAYROLL_ALGORITM','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (65,'PAYROLL_ALGORITM_TYPE','PAYROLL_ALGORITM_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (66,'PAYROLL_FORM','PAYROLL_FORM','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (67,'PAYROLL_GROUP','PAYROLL_GROUP','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (68,'PAYROLL_MODE','PAYROLL_MODE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (69,'PAYROLL_TYPE','PAYROLL_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (70,'PERIOD','PERIOD','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (71,'PERIOD_TYPE','PERIOD_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (72,'PERSON','PERSON','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (73,'PERSON_DOCUMENT_TYPE','PERSON_DOCUMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (74,'PHONE_TYPE','PHONE_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (75,'JOB_POSITION','JOB_POSITION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (76,'PRICE_TYPE','PRICE_TYPE','ENTITY');

INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (80,'PRODUCT_GROUP','PRODUCT_GROUP','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (81,'PRODUCT_SECTION','PRODUCT_SECTION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (82,'PROJECT','PROJECT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (83,'PROJECT_ROLE','PROJECT_ROLE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (84,'PROJECT_STAGE','PROJECT_STAGE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (85,'PROJECT_STAGE_GROUP','PROJECT_STAGE_GROUP','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (86,'PROJECT_STATUS','PROJECT_STATUS','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (87,'PROJECT_TYPE','PROJECT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (88,'PURCHASE_ORDER','PURCHASE_ORDER','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (89,'PURCHASE_PLAN','PURCHASE_PLAN','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (90,'REGION','REGION','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (91,'RESPONSIBLE','RESPONSIBLE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (92,'SALE_ORDER','SALE_ORDER','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (93,'SALE_PLAN','SALE_PLAN','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (94,'SICKLIST_AVERANGE_TYPE','SICKLIST_AVERANGE_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (95,'SICKLIST_TYPE','SICKLIST_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (96,'SICK_TYPE','SICK_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (97,'SPECIALITY','SPECIALITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (98,'WAREHOUSE','WAREHOUSE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (99,'STORE','STORE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (100,'STREET_TYPE','STREET_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (101,'SYS_ROLE','SYS_ROLE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (102,'SYS_USER','SYS_USER','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (103,'SYS_VARIABLE','SYS_VARIABLE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (104,'TASK','TASK','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (105,'TASK_PRIORITY','TASK_PRIORITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (106,'TASK_RESULT','TASK_RESULT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (107,'TASK_ROLE','TASK_ROLE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (108,'TASK_STATUS','TASK_STATUS','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (109,'TASK_TYPE','TASK_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (110,'TAX','TAX','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (111,'TAXPRINT_TYPE','TAXPRINT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (112,'SALE_TAX_WAYBILL','SALE_TAX_WAYBILL','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (113,'TEMPLATE_ENTRY','TEMPLATE_ENTRY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (114,'UNIT','UNIT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (115,'DOCUMENT','DOCUMENT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (116,'PURCHASE_INVOICE','PURCHASE_INVOICE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (117,'PURCHASE_SERV','PURCHASE_SERV','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (118,'PURCHASE_TAX_WAYBILL','PURCHASE_TAX_WAYBILL','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (119,'INVENTORY_INCOME','INVENTORY_INCOME','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (120,'INVENTORY_OUTCOME','INVENTORY_OUTCOME','ENTITY');

INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (121,'DOCUMENT_STATUS','DOCUMENT_STATUS','ENTITY');

INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (130,'PIM_APPOINTMENT_PRIORITY','PIM_APPOINTMENT_PRIORITY','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (131,'PIM_APPOINTMENT_TYPE','PIM_APPOINTMENT_TYPE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (132,'PIM_APPOINTMENT','PIM_APPOINTMENT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (133,'PIM_EVENT','PIM_EVENT','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (134,'PIM_NOTE','PIM_NOTE','ENTITY');
INSERT INTO SYS_SECURE_OBJECT (ID, OBJECT_ID, CODE, OBJECT_TYPE) VALUES (135,'PIM_REMINDER','PIM_REMINDER','ENTITY');



INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (1,1,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (2,2,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (3,3,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (4,4,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (5,5,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (6,6,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (7,7,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (8,8,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (9,9,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (10,10,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (11,11,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (12,12,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (13,13,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (14,14,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (15,15,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (16,16,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (17,17,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (18,18,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (19,19,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (20,20,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (21,21,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (22,22,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (23,23,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (24,24,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (25,25,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (26,26,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (27,27,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (28,28,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (29,29,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (30,30,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (31,31,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (32,32,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (33,33,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (34,34,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (35,35,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (36,36,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (37,37,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (38,38,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (39,39,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (40,40,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (41,41,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (42,42,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (43,43,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (44,44,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (45,45,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (46,46,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (47,47,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (48,48,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (49,49,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (50,50,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (51,51,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (52,52,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (53,53,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (54,54,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (55,55,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (56,56,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (57,57,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (58,58,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (59,59,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (60,60,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (61,61,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (62,62,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (63,63,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (64,64,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (65,65,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (66,66,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (67,67,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (68,68,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (69,69,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (70,70,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (71,71,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (72,72,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (73,73,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (74,74,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (75,75,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (76,76,1,'Y','Y','N','N','N');

INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (80,80,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (81,81,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (82,82,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (83,83,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (84,84,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (85,85,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (86,86,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (87,87,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (88,88,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (89,89,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (90,90,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (91,91,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (92,92,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (93,93,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (94,94,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (95,95,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (96,96,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (97,97,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (98,98,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (99,99,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (100,100,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (101,101,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (102,102,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (103,103,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (104,104,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (105,105,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (106,106,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (107,107,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (108,108,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (109,109,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (110,110,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (111,111,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (112,112,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (113,113,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (114,114,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (115,115,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (116,116,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (117,117,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (118,118,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (119,119,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (120,120,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (121,121,1,'Y','Y','N','N','N');

INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (130,130,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (131,131,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (132,132,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (133,133,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (134,134,1,'Y','Y','N','N','N');
INSERT INTO SYS_PERMISSION (ID, SECURE_OBJECT_ID, ROLE_ID, IS_READ, IS_WRITE, IS_EXEC, IS_TYPE_READ, IS_TYPE_WRITE) VALUES (135,135,1,'Y','Y','N','N','N');


/* BUSINESSABLE ENTITITES:      */
/* -----------------------------*/
/* DEPARTMENT                   */ 
/* STORE                        */
/* RESPONSIBLE                  */
/* PARTNER                      */
/* BANK                         */
/* GOODS                        */ 
/* EMPLOYEE                     */
/* PERSON                       */

INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (1, 'DEPARTMENT');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (2, 'STORE');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (9, 'MTRL_RESPONSIBLE');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (10, 'PARTNER');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (11, 'BANK');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (12, 'GOODS');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (13, 'EMPLOYEE');
INSERT INTO BUSINESSABLE_ENTITY (ID, ENTITY_ID) VALUES (14, 'PERSON');



/* STORE                */

INSERT INTO WAREHOUSE_ENTITY (ID, ENTITY_ID) VALUES (1, 'STORE');




/* PARTNER              */
/* PERSON               */
/* EMPLOYEE             */
/* BANK                 */

INSERT INTO CONTACTABLE_ENTITY (ID, ENTITY_ID) VALUES (1, 'PARTNER');
INSERT INTO CONTACTABLE_ENTITY (ID, ENTITY_ID) VALUES (2, 'PERSON');
INSERT INTO CONTACTABLE_ENTITY (ID, ENTITY_ID) VALUES (3, 'EMPLOYEE');
INSERT INTO CONTACTABLE_ENTITY (ID, ENTITY_ID) VALUES (4, 'BANK');



/* ------------------------------------------------------------------------------------------------------------ */
/* DICTIONARY INITIALIZATION                                                                                    */
/* ------------------------------------------------------------------------------------------------------------ */

/*
'GOODS_REST'
'GOODS_INCOME'
'GOODS_OUTCOME'
'GOODS_MOVE'
'GOODS_WRITEOFF'
'PAYMENT_INCOME'
'PAYMENT_OUTCOME'
'EMPLOYEE_RECEPTION'
'EMPLOYEE_DISCHARGE'
'EMPLOYEE_VACATION'
'EMPLOYEE_SICKLIST'
'SALE_INVOICE'
'CONTRACT'
*/


INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (1, 'INVENTORY_REST','INVENTORY', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (2, 'GOODS_INCOME','GOODS', 'PURCHASE');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (3, 'GOODS_OUTCOME','GOODS', 'SALE');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (4, 'INVENTORY_MOVE','INVENTORY', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (5, 'INVENTORY_WRITEOFF','INVENTORY', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (6, 'PAYMENT_INCOME','PAYMENT', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (7, 'PAYMENT_OUTCOME','PAYMENT', 'PAYMENT');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (8, 'EMPLOYEE_RECEPTION','HR', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (9, 'EMPLOYEE_DISCHARGE','HR', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (10, 'EMPLOYEE_VACATION','HR', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (11, 'EMPLOYEE_SICKLIST','HR', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (12, 'SALE_INVOICE','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (13, 'CONTRACT','DOCUMENT', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (14, 'SALE_ORDER','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (15, 'PURCHASE_ORDER','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (16, 'SALE_TAX_WAYBILL','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (17, 'SALE_PLAN','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (18, 'PURCHASE_PLAN','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (19, 'SALE_SERV','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (20, 'CASH_INCOME','CASH', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (21, 'CASH_OUTCOME','CASH', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (22, 'PURCHASE_INVOICE','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (23, 'PURCHASE_SERV','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (24, 'PURCHASE_TAX_WAYBILL','GOODS', NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (25, 'INVENTORY_INCOME','INVENTORY', 'PURCHASE');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (26, 'INVENTORY_OUTCOME','INVENTORY', 'SALE');


INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (1000, '<SYS_ROW>','<SYS_ROW>', NULL);


INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (1, 1, 'REST', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (2, 2, 'INPUT', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (3, 3, 'OUTPUT', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (4, 4, 'ROTATE', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (5, 5, 'OUTPUT', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (6, 6, 'INPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (7, 7, 'OUTPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (8, 12, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (9, 13, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (10, 14, 'ORDER_OUTPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (11, 15, 'ORDER_INPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (12, 16, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (13, 17, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (14, 18, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (15, 19, 'OUTPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (16, 20, 'INPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (17, 21, 'OUTPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (18, 22, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (19, 23, 'OUTPUT', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (20, 24, 'NONE', 'Y');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (21, 25, 'INPUT', 'N');
INSERT INTO FINANCE_DOCUMENT_TYPE (ID, DOCUMENT_TYPE_ID, MOVE_TYPE, IS_INCLUDE_TAX_IN_AMOUNT) VALUES (22, 26, 'OUTPUT', 'N');


INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (101, 1, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (201, 2, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (301, 3, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (401, 4, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (501, 5, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (601, 6, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (701, 7, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (801, 8, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (901, 9, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1001, 10, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1101, 11, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1201, 12, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1301, 13, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1401, 14, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1501, 15, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1601, 16, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1701, 17, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1801, 18, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1901, 19, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2001, 20, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2101, 21, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2201, 22, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2301, 23, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2401, 24, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2501, 25, 'CREATED', 'Создан', 'Y', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2601, 26, 'CREATED', 'Создан', 'Y', 'N', 'Y');


INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1202, 12, 'PAID', 'Оплачен', 'N', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1402, 14, 'PAID', 'Оплачен', 'N', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1502, 15, 'PAID', 'Оплачен', 'N', 'N', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2202, 22, 'PAID', 'Оплачен', 'N', 'N', 'Y');

INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1203, 12, 'CALCELED', 'Отменён', 'N', 'Y', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1403, 14, 'CALCELED', 'Отменён', 'N', 'Y', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1503, 15, 'CALCELED', 'Отменён', 'N', 'Y', 'Y');
INSERT INTO DOCUMENT_STATUS (ID, DOCUMENT_TYPE_ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2203, 22, 'CALCELED', 'Отменён', 'N', 'Y', 'Y');



/* SALE_ORDER */
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (1, 14, 12,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (2, 14, 6, 'org.plazmaforge.bsolution.bank.common.PaymentDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (3, 14, 3, 'org.plazmaforge.bsolution.product.common.WarehouseProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (4, 14, 16,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (5, 14, 13,'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
	
/* SALE_INVOICE */
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (10, 12, 3, 'org.plazmaforge.bsolution.product.common.OutcomeWarehouseProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (11, 12, 16,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (12, 12, 6, 'org.plazmaforge.bsolution.bank.common.PaymentDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (13, 12, 13,'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
	
/* PURCHASE_ORDER */
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (20, 15, 22,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (21, 15, 7, 'org.plazmaforge.bsolution.bank.common.PaymentDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (22, 15, 2, 'org.plazmaforge.bsolution.product.common.WarehouseProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (23, 15, 24,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (24, 15, 13,'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
	
/* PURCHASE_INVOICE */
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (30, 22, 2, 'org.plazmaforge.bsolution.product.common.IncomeWarehouseProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (31, 22, 24,'org.plazmaforge.bsolution.product.common.ProductDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (32, 22, 7, 'org.plazmaforge.bsolution.bank.common.PaymentDocumentCreator');
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (33, 22, 13,'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	

/* CONTRACT */
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (40, 13, 14, 'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (41, 13, 12, 'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (42, 13, 15, 'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	
INSERT INTO DOCUMENT_RELATION (ID, PARENT_TYPE_ID, CHILD_TYPE_ID, CREATOR_CLASS) VALUES (43, 13, 22, 'org.plazmaforge.bsolution.finance.common.FinanceDocumentCreator');	


INSERT INTO PERIOD_TYPE (ID, CODE, NAME) VALUES (1, 'MONTH', 'Месяц');
INSERT INTO PERIOD_TYPE (ID, CODE, NAME) VALUES (2, 'QUARTER', 'Квартал');
INSERT INTO PERIOD_TYPE (ID, CODE, NAME) VALUES (3, 'YEAR', 'Год');
INSERT INTO PERIOD_TYPE (ID, CODE, NAME) VALUES (100, 'CUSTOM', 'Произвольный');



INSERT INTO UNIT (ID, CODE, NAME, FULL_NAME) VALUES (1, '001', 'шт', 'штука');
INSERT INTO UNIT (ID, CODE, NAME, FULL_NAME) VALUES (2, '002', 'кг', 'килограмм');
INSERT INTO UNIT (ID, CODE, NAME, FULL_NAME) VALUES (3, '003', 'м', 'метр');
INSERT INTO UNIT (ID, CODE, NAME, FULL_NAME) VALUES (4, '004', 'м2', 'метр квадратный');







/* ------------------------------------------------------------------------------------------------------------ */
/* CONTACT INITIALIZATION                                                                                       */
/* ------------------------------------------------------------------------------------------------------------ */



/* ------------------------------------------------------------------------------------------------------------ */
/* PRODUCT INITIALIZATION                                                                                       */
/* ------------------------------------------------------------------------------------------------------------ */


INSERT INTO PRODUCT_SECTION (ID, CODE, NAME) VALUES (1,'GOODS','Номенклатура');
INSERT INTO PRODUCT_SECTION (ID, CODE, NAME) VALUES (2,'ASSET','Основные средства');
INSERT INTO PRODUCT_SECTION (ID, CODE, NAME) VALUES (3,'INTANGIBLE','Нематериальные активы');


INSERT INTO GOODS_TYPE (ID, CODE, NAME) VALUES (1, 'GOODS', 'Товар');
INSERT INTO GOODS_TYPE (ID, CODE, NAME) VALUES (2, 'SERVICE', 'Услуга');
INSERT INTO GOODS_TYPE (ID, CODE, NAME) VALUES (3, 'SET', 'Набор');
INSERT INTO GOODS_TYPE (ID, CODE, NAME) VALUES (4, 'PRODUCT', 'Продукция');
INSERT INTO GOODS_TYPE (ID, CODE, NAME) VALUES (5, 'WORK', 'Работа');

INSERT INTO FORM_PROPERTY (ID, NAME) VALUES (1,'ООО');
INSERT INTO FORM_PROPERTY (ID, NAME) VALUES (2,'ЗАО');
INSERT INTO FORM_PROPERTY (ID, NAME) VALUES (3,'АО');

INSERT INTO PRICE_TYPE (ID, NAME, PRICE_PERCENT) VALUES (1,'Базовая', 0);
INSERT INTO PRICE_TYPE (ID, NAME, PRICE_PERCENT) VALUES (2,'Оптовая', 0);
INSERT INTO PRICE_TYPE (ID, NAME, PRICE_PERCENT) VALUES (3,'Розничная', 0);
INSERT INTO PRICE_TYPE (ID, NAME, PRICE_PERCENT) VALUES (4,'Закупочная', 0);

INSERT INTO TAX (ID, CODE, NAME, TAX_PERCENT, AMOUNT) VALUES (1, 'НДС', 'НДС', 20.0, 0.0);

INSERT INTO LEDGER_ACCOUNT_TYPE (ID, CODE, NAME) VALUES (1, 'А', 'Активный');
INSERT INTO LEDGER_ACCOUNT_TYPE (ID, CODE, NAME) VALUES (2, 'П', 'Пассивный');
INSERT INTO LEDGER_ACCOUNT_TYPE (ID, CODE, NAME) VALUES (3, 'АП', 'Активно-пассивный');

INSERT INTO PARTNER_TYPE (ID, NAME) VALUES (1, 'Юридическое лицо');
INSERT INTO PARTNER_TYPE (ID, NAME) VALUES (2, 'Физическое лицо');

/* ------------------------------------------------------------------------------------------------------------ */
/* CONTEXT INITIALIZATION                                                                                       */
/* ------------------------------------------------------------------------------------------------------------ */


/* BSS = 1 */
INSERT INTO PARTNER (ID, CODE, NAME) VALUES (1, '111', 'Моя компания');
INSERT INTO BUSINESSABLE (ID, OWNER_ID, ENTITY_ID) VALUES (1, 1, 'PARTNER');
INSERT INTO CONTACTABLE (ID, OWNER_ID, ENTITY_ID) VALUES (1, 1, 'PARTNER');

INSERT INTO CONTRACTOR (ID) VALUES (1);

INSERT INTO ORGANIZATION (ID) VALUES (1);

INSERT INTO PERIOD (ID, PERIOD_TYPE_ID, START_DATE, END_DATE, NAME) VALUES (1, 1, '2011-01-01', '2011-03-31', '01 января 2011 - 31 марта 2011');

INSERT INTO SYS_INFO (ID, ORGANIZATION_ID, IS_INIT, APP_VERSION, DB_VERSION, APP_BUILD, DB_BUILD) VALUES (1, 1, 'N', '1.0.2', '1.0.2', '20120717', '20120717');
INSERT INTO SYS_PREFERENCE (ID) VALUES (1);
INSERT INTO ENTERPRISE_CONTEXT (ID, CURRENCY_ID, PERIOD_ID, UNIT_ID) VALUES (1, 1, 1, 1);


/* BSS = 2 FIRST CONTACT */

INSERT INTO CONTACT (ID, ORGANIZATION_ID, CONTACT_TYPE_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, NAME, GENDER) VALUES (2, 1, 1, 'Администратор', NULL, NULL, 'Администратор', 1);
INSERT INTO CONTACTABLE (ID, OWNER_ID, ENTITY_ID) VALUES (2, 2, 'CONTACT');
UPDATE SYS_USER SET CONTACT_ID = 2;



INSERT INTO CONTACT_CONTEXT (ID, RESPONSIBLE_ID, CONTACT_TYPE_ID, ADDRESS_TYPE_ID, PHONE_TYPE_ID) VALUES (1, NULL, 1, 4, 16);
INSERT INTO BANK_CONTEXT (ID) VALUES (1);
INSERT INTO PROJECT_CONTEXT (ID) VALUES (1);
INSERT INTO TASK_CONTEXT (ID) VALUES (1);
