
CREATE TABLE HELLO (
 ID INTEGER PRIMARY KEY,
 HELLO_MESSAGE VARCHAR(50)
);


INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (1,'Hello 1');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (2,'Hello 2');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (3,'Hello 3');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (4,'Hello 4');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (5,'Hello 5');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (6,'Hello 6');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (7,'Hello 7');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (8,'Hello 8');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (9,'Hello 9');

INSERT INTO HELLO (ID, HELLO_MESSAGE) VALUES (10,'Hello 10');
