
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (1, 232, 'Missoury');
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (2, 232, 'Kansas');
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (3, 232, 'California');
