
/*===================================================*/
/*                                                   */
/* Update system                                     */
/*                                                   */
/*===================================================*/
/* 1. Rename entities
/*===================================================*/


/* SYSTEM_ENTITY */

 UPDATE SYSTEM_ENTITY SET ID = 'SALE_INVOICE', CODE =  'SALE_INVOICE' WHERE ID = 'INVOICE';
 UPDATE SYSTEM_ENTITY SET ID = 'SALE_INVOICE_ITEM', CODE =  'SALE_INVOICE_ITEM' WHERE ID = 'INVOICE_ITEM';
 UPDATE SYSTEM_ENTITY SET ID = 'SALE_SERV', CODE =  'SALE_SERV' WHERE ID = 'EXEC_WORK';
 UPDATE SYSTEM_ENTITY SET ID = 'SALE_SERV_ITEM', CODE =  'SALE_SERV_ITEM' WHERE ID = 'EXEC_WORK_ITEM';
 UPDATE SYSTEM_ENTITY SET ID = 'SALE_TAX_WAYBILL', CODE =  'SALE_TAX_WAYBILL' WHERE ID = 'TAX_WAYBILL';
 UPDATE SYSTEM_ENTITY SET ID = 'SALE_TAX_WAYBILL_ITEM', CODE =  'SALE_TAX_WAYBILL_ITEM' WHERE ID = 'TAX_WAYBILL_ITEM';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_REST', CODE =  'INVENTORY_REST' WHERE ID = 'GOODS_REST';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_REST_ITEM', CODE =  'INVENTORY_REST_ITEM' WHERE ID = 'GOODS_REST_ITEM';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_MOVE', CODE =  'INVENTORY_MOVE' WHERE ID = 'GOODS_MOVE';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_MOVE_ITEM', CODE =  'INVENTORY_MOVE_ITEM' WHERE ID = 'GOODS_MOVE_ITEM';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_WRITEOFF', CODE =  'INVENTORY_WRITEOFF' WHERE ID = 'GOODS_WRITEOFF';
 UPDATE SYSTEM_ENTITY SET ID = 'INVENTORY_WRITEOFF_ITEM', CODE =  'INVENTORY_WRITEOFF_ITEM' WHERE ID = 'GOODS_WRITEOFF_ITEM';



/* DOCUMENT_TYPE */

 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_INVOICE' WHERE ENTITY_ID = 'INVOICE';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_INVOICE_ITEM' WHERE ENTITY_ID = 'INVOICE_ITEM';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_SERV' WHERE ENTITY_ID = 'EXEC_WORK';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_SERV_ITEM' WHERE ENTITY_ID = 'EXEC_WORK_ITEM';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_TAX_WAYBILL' WHERE ENTITY_ID = 'TAX_WAYBILL';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'SALE_TAX_WAYBILL_ITEM' WHERE ENTITY_ID = 'TAX_WAYBILL_ITEM';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_REST' WHERE ENTITY_ID = 'GOODS_REST';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_REST_ITEM' WHERE ENTITY_ID = 'GOODS_REST_ITEM';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_MOVE' WHERE ENTITY_ID = 'GOODS_MOVE';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_MOVE_ITEM' WHERE ENTITY_ID = 'GOODS_MOVE_ITEM';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_WRITEOFF' WHERE ENTITY_ID = 'GOODS_WRITEOFF';
 UPDATE DOCUMENT_TYPE SET ENTITY_ID = 'INVENTORY_WRITEOFF_ITEM' WHERE ENTITY_ID = 'GOODS_WRITEOFF_ITEM';


 
/* SECURE_OBJECT */

 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_INVOICE', CODE =  'SALE_INVOICE' WHERE ENTITY_ID = 'INVOICE';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_INVOICE_ITEM', CODE =  'SALE_INVOICE_ITEM' WHERE ENTITY_ID = 'INVOICE_ITEM';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_SERV', CODE =  'SALE_SERV' WHERE ENTITY_ID = 'EXEC_WORK';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_SERV_ITEM', CODE =  'SALE_SERV_ITEM' WHERE ENTITY_ID = 'EXEC_WORK_ITEM';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_TAX_WAYBILL', CODE =  'SALE_TAX_WAYBILL' WHERE ENTITY_ID = 'TAX_WAYBILL';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'SALE_TAX_WAYBILL_ITEM', CODE =  'SALE_TAX_WAYBILL_ITEM' WHERE ENTITY_ID = 'TAX_WAYBILL_ITEM';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_REST', CODE =  'INVENTORY_REST' WHERE ENTITY_ID = 'GOODS_REST';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_REST_ITEM', CODE =  'INVENTORY_REST_ITEM' WHERE ENTITY_ID = 'GOODS_REST_ITEM';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_MOVE', CODE =  'INVENTORY_MOVE' WHERE ENTITY_ID = 'GOODS_MOVE';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_MOVE_ITEM', CODE =  'INVENTORY_MOVE_ITEM' WHERE ENTITY_ID = 'GOODS_MOVE_ITEM';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_WRITEOFF', CODE =  'INVENTORY_WRITEOFF' WHERE ENTITY_ID = 'GOODS_WRITEOFF';
 UPDATE SECURE_OBJECT SET ENTITY_ID = 'INVENTORY_WRITEOFF_ITEM', CODE =  'INVENTORY_WRITEOFF_ITEM' WHERE ENTITY_ID = 'GOODS_WRITEOFF_ITEM';



/* SYSTEM_ATTR */

 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_INVOICE' WHERE ENTITY_ID = 'INVOICE';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_INVOICE_ITEM' WHERE ENTITY_ID = 'INVOICE_ITEM';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_SERV' WHERE ENTITY_ID = 'EXEC_WORK';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_SERV_ITEM' WHERE ENTITY_ID = 'EXEC_WORK_ITEM';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_TAX_WAYBILL' WHERE ENTITY_ID = 'TAX_WAYBILL';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'SALE_TAX_WAYBILL_ITEM' WHERE ENTITY_ID = 'TAX_WAYBILL_ITEM';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_REST' WHERE ENTITY_ID = 'GOODS_REST';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_REST_ITEM' WHERE ENTITY_ID = 'GOODS_REST_ITEM';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_MOVE' WHERE ENTITY_ID = 'GOODS_MOVE';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_MOVE_ITEM' WHERE ENTITY_ID = 'GOODS_MOVE_ITEM';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_WRITEOFF' WHERE ENTITY_ID = 'GOODS_WRITEOFF';
 UPDATE SYSTEM_ATTR SET ENTITY_ID = 'INVENTORY_WRITEOFF_ITEM' WHERE ENTITY_ID = 'GOODS_WRITEOFF_ITEM';



/* SYSTEM_ATTR_TYPE */

 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_INVOICE' WHERE ENTITY_ID = 'INVOICE';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_INVOICE_ITEM' WHERE ENTITY_ID = 'INVOICE_ITEM';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_SERV' WHERE ENTITY_ID = 'EXEC_WORK';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_SERV_ITEM' WHERE ENTITY_ID = 'EXEC_WORK_ITEM';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_TAX_WAYBILL' WHERE ENTITY_ID = 'TAX_WAYBILL';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'SALE_TAX_WAYBILL_ITEM' WHERE ENTITY_ID = 'TAX_WAYBILL_ITEM';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_REST' WHERE ENTITY_ID = 'GOODS_REST';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_REST_ITEM' WHERE ENTITY_ID = 'GOODS_REST_ITEM';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_MOVE' WHERE ENTITY_ID = 'GOODS_MOVE';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_MOVE_ITEM' WHERE ENTITY_ID = 'GOODS_MOVE_ITEM';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_WRITEOFF' WHERE ENTITY_ID = 'GOODS_WRITEOFF';
 UPDATE SYSTEM_ATTR_TYPE SET ENTITY_ID = 'INVENTORY_WRITEOFF_ITEM' WHERE ENTITY_ID = 'GOODS_WRITEOFF_ITEM';



 /* SYSTEM_ATTR_TYPE_GROUP */

 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_INVOICE' WHERE ENTITY_ID = 'INVOICE';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_INVOICE_ITEM' WHERE ENTITY_ID = 'INVOICE_ITEM';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_SERV' WHERE ENTITY_ID = 'EXEC_WORK';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_SERV_ITEM' WHERE ENTITY_ID = 'EXEC_WORK_ITEM';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_TAX_WAYBILL' WHERE ENTITY_ID = 'TAX_WAYBILL';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'SALE_TAX_WAYBILL_ITEM' WHERE ENTITY_ID = 'TAX_WAYBILL_ITEM';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_REST' WHERE ENTITY_ID = 'GOODS_REST';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_REST_ITEM' WHERE ENTITY_ID = 'GOODS_REST_ITEM';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_MOVE' WHERE ENTITY_ID = 'GOODS_MOVE';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_MOVE_ITEM' WHERE ENTITY_ID = 'GOODS_MOVE_ITEM';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_WRITEOFF' WHERE ENTITY_ID = 'GOODS_WRITEOFF';
 UPDATE SYSTEM_ATTR_TYPE_GROUP SET ENTITY_ID = 'INVENTORY_WRITEOFF_ITEM' WHERE ENTITY_ID = 'GOODS_WRITEOFF_ITEM';

/*===================================================*/
/* 2. Delete entities
/*===================================================*/


/*===================================================*/
/* 3. Insert entities
/*===================================================*/


 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_INVOICE', 'PURCHASE_INVOICE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_INVOICE_ITEM', 'PURCHASE_INVOICE_ITEM', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_SERV', 'PURCHASE_SERV', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_SERV_ITEM', 'PURCHASE_SERV_ITEM', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_TAX_WAYBILL', 'PURCHASE_TAX_WAYBILL', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PURCHASE_TAX_WAYBILL_ITEM', 'PURCHASE_TAX_WAYBILL_ITEM', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('INVENTORY_INCOME', 'INVENTORY_INCOME', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('INVENTORY_INCOME_ITEM', 'INVENTORY_INCOME_ITEM', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('INVENTORY_OUTCOME', 'INVENTORY_OUTCOME', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('INVENTORY_OUTCOME_ITEM', 'INVENTORY_OUTCOME_ITEM', '-', 'ENTITY');


/* ID is started from 22 !!! */

 INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (22, 'PURCHASE_INVOICE','GOODS', NULL);
 INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (23, 'PURCHASE_SERV','GOODS', NULL);
 INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (24, 'PURCHASE_TAX_WAYBILL','GOODS', NULL);
 INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (25, 'INVENTORY_INCOME','INVENTORY', NULL);
 INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (26, 'INVENTORY_OUTCOME','INVENTORY', NULL);
