
INSERT INTO CURRENCY (ID, NUMERIC_CODE, NAME, FULL_NAME, CODE) VALUES (1, '840', 'USD', 'US Dollar','USD');
INSERT INTO CURRENCY (ID, NUMERIC_CODE, NAME, FULL_NAME, CODE) VALUES (2, '978', 'EUR', 'Euro','EUR');
