


INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (1, 3, 4, 1, '002', '003', 'Doc.Amount', 'Doc.Warehouse', 'Doc.Partner', 'Goods income');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (2, 5, 4, 1, '004', '003', 'Doc.TaxAmount', 'Doc.Partner', 'Doc.Partner', 'Tax');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (3, 9, 7, 2, '013', '011', 'Doc.AmountWithTax', 'Doc.Partner', '', 'Goods outcome');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (4, 7, 10, 2, '011', '014', 'Doc.TaxAmount', '', 'Doc.Partner', 'Tax');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (5, 16, 3, 2, '025', '002', 'Doc.Amount', '', 'Doc.Warehouse', 'Goods outcome (Warehouse)');





