

INSERT INTO TEMPLATE_ENTRY (ID, FINANCE_DOCUMENT_TYPE_ID, CODE, NAME) VALUES (1, 2, '001', 'Goods Income');
INSERT INTO TEMPLATE_ENTRY (ID, FINANCE_DOCUMENT_TYPE_ID, CODE, NAME) VALUES (2, 3, '002', 'Goods Outcome');
