

INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (1, 1, NULL, '1000', 'Товар');
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (2, 1, NULL, '2000', 'Услуги');



INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (1,'Электронно');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (2,'Почтой');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (3,'Телеграфом');

INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (1,'Указывать в тексте сумму и НДС');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (2,'Указывать в тексте только НДС');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (3,'Указывать в тексте только сумму');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (4,'не указывать в тексте сумму и НДС');

