
CREATE VIEW V_RPT_PARTNER_ROTATE (
 ORGANIZATION_ID,
 PERIOD_ID, 
 PARTNER_ID,
 REST_CREDIT_AMOUNT, 
 REST_DEBIT_AMOUNT, 
 CREDIT_AMOUNT,
 DEBIT_AMOUNT
) AS
SELECT 
 R.ORGANIZATION_ID,
 R.PERIOD_ID, 
 R.PARTNER_ID,
 CAST(R.CREDIT_AMOUNT AS NUMERIC(9, 2)) AS REST_CREDIT_AMOUNT, 
 CAST(R.DEBIT_AMOUNT AS NUMERIC(9, 2)) AS REST_DEBIT_AMOUNT, 
 CAST(0.0 AS NUMERIC(9, 2)) AS CREDIT_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 2)) AS DEBIT_AMOUNT
FROM V_RPT_PARTNER_REST_START R
UNION ALL 
SELECT 
 C.ORGANIZATION_ID,
 C.PERIOD_ID, 
 C.PARTNER_ID,
 CAST(0.0 AS NUMERIC(9, 2)) AS REST_CREDIT_AMOUNT, 
 CAST(0.0 AS NUMERIC(9, 2)) AS REST_DEBIT_AMOUNT, 
 CAST(C.AMOUNT AS NUMERIC(9, 2)) AS CREDIT_AMOUNT,
 CAST(0.0 AS NUMERIC(9, 2)) AS DEBIT_AMOUNT
FROM V_RPT_PARTNER_CREDIT_FULL C
UNION ALL 
SELECT 
 D.ORGANIZATION_ID,
 D.PERIOD_ID, 
 D.PARTNER_ID,
 CAST(0.0 AS NUMERIC(9, 2)) AS REST_CREDIT_AMOUNT, 
 CAST(0.0 AS NUMERIC(9, 2)) AS REST_DEBIT_AMOUNT, 
 CAST(0.0 AS NUMERIC(9, 2)) AS CREDIT_AMOUNT,
 CAST(D.AMOUNT AS NUMERIC(9, 2)) AS DEBIT_AMOUNT
 FROM V_RPT_PARTNER_DEBIT_FULL D;
