


INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (4, 'Клиенты');
INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (5, 'Страховщики');
INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (6, 'Брокеры');



INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (204, 1, '3000', 'Материалы', NULL, NULL);
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (205, 1, '4000', 'Запчасти', NULL, NULL);
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (206, 1, '5000', 'Краска', NULL, NULL);


INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR','CAR','Автомобиль','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_INSURER_CONTRACT_VARIANT','CAR_INSURER_CONTRACT_VARIANT','Договор по страховщику','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');


INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_PART','CAR_PART','Запчасть (автосервис)','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV','CAR_SERV','Услуги (автосервис)','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_PAINT','CAR_PAINT','Краска и консумативы (автосервис)','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_DETAIL','CAR_DETAIL','Детали (автосервис)','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV_ORDER','CAR_SERV_ORDER','Заказ (автосервис)','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV_ORDER_ITEM','CAR_SERV_ORDER_ITEM','Строчки заказа (автосервис)','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');



INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REQUEST','CAR_MTRL_FIND_REQUEST','Заявка на поиск материала','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REQUEST_ITEM','CAR_MTRL_FIND_REQUEST_ITEM','Строчки заявки на поиск материала','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REPORT','CAR_MTRL_FIND_REPORT','Отчёт по поиску материала','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REPORT_ITEM','CAR_MTRL_FIND_REPORT_ITEM','Строчки отчёта по поиску материала','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');



INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REQUEST','CAR_MTRL_PURCHASE_REQUEST','Заявка на закупку материала','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REQUEST_ITEM','CAR_MTRL_PURCHASE_REQUEST_ITEM','Строчки заявки на закупку материала','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REPORT','CAR_MTRL_PURCHASE_REPORT','Отчёт по закупке материала','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REPORT_ITEM','CAR_MTRL_PURCHASE_REPORT_ITEM','Строчки отчёта по закупке материала','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');

INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (100, 'CAR_SERV_ORDER', 'GOODS', 'SALE');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (101, 'CAR_MTRL_FIND_REQUEST', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (102, 'CAR_MTRL_FIND_REPORT', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (103, 'CAR_MTRL_PURCHASE_REQUEST', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (104, 'CAR_MTRL_PURCHASE_REPORT', NULL, NULL);

/* CAR_SER_ORDER */
UPDATE DOCUMENT_TYPE SET DOCUMENT_CODE_PREFIX = 'C1-', LAST_DOCUMENT_NUMBER = 1000, IS_USE_NUMERATOR = 'Y', IS_DOCUMENT_CODE_READ_ONLY  = 'Y', IS_DOCUMENT_DATE_READ_ONLY = 'Y' WHERE ID = 100;


INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (1, 'Покраска основных деталей');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (2, 'Покраска неосновных деталей');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (3, 'Покраска порогов');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (4, 'Полная покраска');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (5, 'Частичная покраска');




INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (0, 'Замена');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (1, '1');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (2, '2');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (3, '3');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (4, '4');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (5, 'C ремонт');



INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (1, 'Растягивание (степель)');
INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (2, 'Подготовка основных деталей');
INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (3, 'Подготовка неосновных деталей');


INSERT INTO CAR_PAINT_MARK (ID, NAME) VALUES (1, 'Сикенс');
INSERT INTO CAR_PAINT_MARK (ID, NAME) VALUES (2, 'Лезонал');

INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (1, 'Слесарные');
INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (2, 'Рихтовальные');
INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (3, 'Покрасочные');





