
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (1, 'BUSINESS', 'Рабочий');
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (2, 'HOME', 'Домашний');
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (3, 'OTHER', 'Другой');
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (4, 'PRIMARY', 'Основной');
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (5, 'REAL', 'Физический');
INSERT INTO ADDRESS_TYPE (ID, CODE, NAME) VALUES (6, 'POSTAL', 'Почтовый');
