
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (1, 'ASSISTANT', 'Помощник');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (2, 'BUSINESS', 'Рабочий');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (3, 'BUSINESS2', 'Рабочий 2');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (4, 'BUSINESS_FAX', 'Факс рабочий');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (5, 'CALLBACK', 'Ответ на звонок');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (6, 'CAR', 'Автомоб.');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (7, 'COMPANY', 'Организация');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (8, 'HOME', 'Домашний');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (9, 'HOME2', 'Домашний 2');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (10, 'HOME_FAX', 'Факс дом.');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (11, 'ISDN', 'Сеть ISDN');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (12, 'MOBILE', 'Мобильный');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (13, 'OTHER', 'Другой');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (14, 'OTHER_FAX', 'Факс дополн.');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (15, 'PAGER', 'Пейджер');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (16, 'PRIMARY', 'Основной');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (17, 'RADIO', 'Радио');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (18, 'TELEX', 'Телекс');
INSERT INTO PHONE_TYPE (ID, CODE, NAME) VALUES (19, 'TTY_TDD', 'TTY/TDD');


