
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (1, 'LOW', 'Low', 1, 'Y');
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (2, 'NORMAL', 'Normal', 2, 'Y');
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (3, 'HIGH', 'High', 3, 'Y');
