
INSERT INTO PROJECT_TYPE (ID, CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES (1, 'STANDARD', 'Standard project', '', 'Y');
INSERT INTO PROJECT_TYPE (ID, CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES (2, 'NETWORKING', 'Networking', '', 'N');
INSERT INTO PROJECT_TYPE (ID, CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES (3, 'SALE', 'Sale', '', 'N');
INSERT INTO PROJECT_TYPE (ID, CODE, NAME, DESCRIPTION, IS_SYSTEM) VALUES (4, 'SERVICE', 'Service', '', 'N');
