
/* DEPRECATED. DON'T REMOVE */

INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (1,  '01', 'MD-Player');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (2,  '02', 'CD-Player');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (3,  '03', 'MP3-Player');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (4,  '04', 'Video/DVD-Player');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (5,  '05', 'Dictaphone');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (6,  '06', 'Sequencer');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (7,  '07', 'Video camera');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (8,  '08', 'Photo camera');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (9,  '09', 'TV');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (10, '10', 'Radio phone');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (11, '11', 'Mobile phone');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (12, '12', 'Pocket PC');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (13, '13', 'Notebook');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (14, '14', 'Translator');
