
INSERT INTO PROJECT_STAGE (ID, PROJECT_TYPE_ID, PROJECT_STAGE_GROUP_ID, CODE, NAME, DESCRIPTION, ORDER_NUMBER, AVERANGE_DURATION, FROM_BEGIN) VALUES (1,1,1,'1','Payment','',2,3,6);
INSERT INTO PROJECT_STAGE (ID, PROJECT_TYPE_ID, PROJECT_STAGE_GROUP_ID, CODE, NAME, DESCRIPTION, ORDER_NUMBER, AVERANGE_DURATION, FROM_BEGIN) VALUES (2,2,2,'2','Meeting','',1,1,1);
