
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 1,'1','Salary - days',1,0,0,1,1);
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 2,'2','Salary - hours',1,1,0,1,1);
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 3,'3','Contract',1,1,0,1,1);
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 4,'4','Adding',1,4,0,1,1);
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 5,'5','Tax',2,17,0,1,1);
INSERT INTO PAYROLL (ID, CODE, NAME, PAYROLL_TYPE_ID, PRIORITY, PAYROLL_PERCENT, PAYROLL_MODE_ID, PAYROLL_ALGORITM_TYPE_ID) VALUES ( 6,'6','Tax state',2,20,1,1,1);
