
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (1, 'STANDARD', 'Standard task', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (2, 'TODO', 'To-do', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (3, 'CASE', 'Case', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (4, 'MEETING', 'Meeting', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (5, 'PRESENTATION', 'Presentation', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (6, 'TALKS', 'Talks', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (7, 'APPOINTMENT', 'Appointment', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (8, 'PROPOSAL', 'Commercial proposal', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (9, 'DOCUMENTS', 'Prepare documents', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (10,'CONSULTATION', 'Consultation', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (11,'LETTER', 'Letter', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (12,'TESTING',' Testing', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (13,'PAPERWORK', 'Paper work', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (14,'CALL', 'Call', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (15,'CONFERENCE', 'Conference', 'Y');
INSERT INTO TASK_TYPE (ID, CODE, NAME, IS_SYSTEM) VALUES (16,'CONTRACT', 'Contract', 'Y');