INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (4, 'Clients');
INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (5, 'Assurers');
INSERT INTO PARTNER_GROUP (ID, NAME) VALUES (6, 'Brokers');

INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (204, 1, '3000', 'Materials', NULL, NULL);
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (205, 1, '4000', 'Parts', NULL, NULL);
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, CODE, NAME, NAME_EN, PARENT_ID) VALUES (206, 1, '5000', 'Paints', NULL, NULL);


INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR','CAR','Car','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_INSURER_CONTRACT_VARIANT','CAR_INSURER_CONTRACT_VARIANT','Contract by car insurer','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_PART','CAR_PART','Car part','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV','CAR_SERV','Car service','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_PAINT','CAR_PAINT','Car paint','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_DETAIL','CAR_DETAIL','Car detail','DICTIONARY','CARSERVICE','Y','Y','Y','Y','Y','N');



INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV_ORDER','SALE_ORDER','Car service order','DOCUMENT','SALE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_SERV_ORDER_ITEM','CAR_SERV_ORDER_ITEM','Car service order item','DOCUMENT','SALE','Y','N','Y','Y','Y','N');



INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REQUEST','CAR_MTRL_FIND_REQUEST','Request to find car materials','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REQUEST_ITEM','CAR_MTRL_FIND_REQUEST_ITEM','Item of request to find car materials','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REPORT','CAR_MTRL_FIND_REPORT','Result of request to find car materials','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_FIND_REPORT_ITEM','CAR_MTRL_FIND_REPORT_ITEM','Item of result of request to find car materials','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');




INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REQUEST','CAR_MTRL_PURCHASE_REQUEST','Request to purchase car materials','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REQUEST_ITEM','CAR_MTRL_PURCHASE_REQUEST_ITEM','Item of request to purchase car materials','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');

INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REPORT','CAR_MTRL_PURCHASE_REPORT','Result of request to purchase car materials','DOCUMENT','CARSERVICE','Y','Y','Y','Y','Y','N');
INSERT INTO SYS_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID, ENTITY_PACKAGE, IS_ENABLE, IS_MASTER, IS_BEAN, IS_FORM, IS_SECURE, IS_SYSTEM) VALUES ('CAR_MTRL_PURCHASE_REPORT_ITEM','CAR_MTRL_PURCHASE_REPORT_ITEM','Item of result of request to purchase car materials','DOCUMENT','CARSERVICE','Y','N','Y','Y','Y','N');


INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (100, 'CAR_SERV_ORDER','SALE', 'SALE');
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (101, 'CAR_MTRL_FIND_REQUEST', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (102, 'CAR_MTRL_FIND_REPORT', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (103, 'CAR_MTRL_PURCHASE_REQUEST', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (ID, ENTITY_ID, DOCUMENT_SECTION, DOCUMENT_CATEGORY) VALUES (104, 'CAR_MTRL_PURCHASE_REPORT', NULL, NULL);

/* CAR_SERV_ORDER */
UPDATE DOCUMENT_TYPE SET DOCUMENT_CODE_PREFIX = 'C1-', LAST_DOCUMENT_NUMBER = 1000, IS_USE_NUMERATOR = 'Y', IS_DOCUMENT_CODE_READ_ONLY  = 'Y', IS_DOCUMENT_DATE_READ_ONLY = 'Y' WHERE ID = 100;

INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (1, 'Type 1');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (2, 'Type 2');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (3, 'Type 3');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (4, 'Type 4');
INSERT INTO CAR_PAINT_DETAIL_TYPE (ID, NAME) VALUES (5, 'Type 5');




INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (0, 'Replace');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (1, '1');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (2, '2');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (3, '3');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (4, '4');
INSERT INTO CAR_DAMAGE_LEVEL (ID, NAME) VALUES (5, 'C repair');



INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (1, 'Type 1');
INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (2, 'Type 2');
INSERT INTO CAR_PREPARE_TYPE (ID, NAME) VALUES (3, 'Type 3');


INSERT INTO CAR_PAINT_MARK (ID, NAME) VALUES (1, 'Mark 1');
INSERT INTO CAR_PAINT_MARK (ID, NAME) VALUES (2, 'Mark 2');


INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (1, 'Service type 1');
INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (2, 'Service type 2');
INSERT INTO CAR_SERV_TYPE (ID, NAME) VALUES (3, 'Service type 3');