


INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (1, 92, 209, 1, '281', '631', 'Doc.Amount', 'Doc.Warehouse', 'Doc.Partner', 'Оприходование ТМЦ');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (2, 225, 209, 1, '644', '631', 'Doc.TaxAmount', 'Doc.Partner', 'Doc.Partner', 'Отражение расчётов по налоговому кредиту (НДС)');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (3, 122, 257, 2, '361', '702', 'Doc.AmountWithTax', 'Doc.Partner', '', 'Отгрузка товара покупателю');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (4, 257, 221, 2, '702', '643', 'Doc.TaxAmount', '', 'Doc.Partner', 'Отражение расчётов по налоговым обязательствам (НДС)');
INSERT INTO TEMPLATE_ENTRY_ITEM (ID, DEBIT_LEDACC_ID, CREDIT_LEDACC_ID, TEMPLATE_ENTRY_ID, DEBIT_LEDACC_EXP, CREDIT_LEDACC_EXP, AMOUNT_EXP, DEBIT_OBJECT_EXP, CREDIT_OBJECT_EXP, CONTENT) VALUES (5, 330, 92, 2, '902', '281', 'Doc.Amount', '', 'Doc.Warehouse', 'Списание себестоимости реализованых товаров');



