
INSERT INTO SYS_QUARTER (ID, QUARTER_NUMBER, NAME) VALUES (1, 1, 'I  ');
INSERT INTO SYS_QUARTER (ID, QUARTER_NUMBER, NAME) VALUES (2, 2, 'II ');
INSERT INTO SYS_QUARTER (ID, QUARTER_NUMBER, NAME) VALUES (3, 3, 'III');
INSERT INTO SYS_QUARTER (ID, QUARTER_NUMBER, NAME) VALUES (4, 4, 'IV ');
