
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (1,1,'101','Перезвонить');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (2,1,'102','Письмо-резюме');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (3,1,'103','Повторная встреча');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (4,2,'201','Интерес отсутствует');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (5,2,'202','Коммерческое предложение');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (6,2,'203','Ожидать встречный звонок');
INSERT INTO TASK_RESULT (ID, TASK_TYPE_ID, CODE, NAME) VALUES (7,2,'204','Переслать материалы');
