 
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (1, 'PERSON_NAME', 'Физ. лицо (ФИО)' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (2, 'PERSON_NAME_R', 'Физ. лицо (ФИО в род. падеже)' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (3, 'DIRECTOR_NAME', 'Директор (ФИО)' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (4, 'GENERAL_ACCOUNTANT_NAME', 'Главный бухгалтер (ФИО)' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (5, 'ORGANIZATION_ACTIVITY', 'Вид деятельности' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (6, 'ORGANIZATION_ACTIVITY_Y_<Г>', 'Вид деятельности в <Г> году' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (7, 'ORGANIZATION_ACTIVITY_YQ_<Г>_<К>', 'Вид деятельности в <Г> году, <К> квартале' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (8, 'ORGANIZATION_TAX_TYPE', 'Тип налога' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (9, 'EMPLOYEE_COUNT', 'Количество работников' , 'INTEGER');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (10, 'EMPLOYEE_COUNT_Y_<Г>', 'Количество работников за <Г> год' , 'INTEGER');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (11, 'EMPLOYEE_COUNT_YM_<Г>_<М>', 'Количество работников за <Г> год, <М> месяц' , 'INTEGER');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (12, 'GOV_TAX_ORGANIZATION_NAME', 'Налоговая служба' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (13, 'GOV_PENSION_ORGANIZATION_NAME', 'Пенсионный фонд' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (14, 'GOV_TAX_AMOUNT', 'Ставка единого налога' , 'FLOAT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (15, 'GOV_PENSION_PERCENT_TAX', '% отчислений в пенсионный фонд от единого налога' , 'FLOAT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (16, 'GOV_PENSION_PERCENT', '% отчислений в пенсионный фонд от заработной платы' , 'FLOAT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (17, 'ORGANIZATION_PENSION_REG_CODE', 'Код регистрации в пенсионном фонде' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (18, 'ORGANIZATION_PENSION_REG_DATE', 'Дата регистрации в пенсионном фонде' , 'DATE');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (19, 'GOV_TAX_DOCUMENT_MARKER', 'Маркер документа для уплаты налога' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID, VALUE_ENTITY_ID) VALUES (20, 'GOV_TAX_BANK_ACCOUNT_ID', 'Банковский счёт для уплаты налога' , 'REFERENCE' , 'BANK_ACCOUNT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID, VALUE_ENTITY_ID) VALUES (21, 'GOV_TAX_BANK_ACCOUNT_ID_<N>', 'Банковский счёт <N> для уплаты налога' , 'REFERENCE' , 'BANK_ACCOUNT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID) VALUES (22, 'GOV_PENSION_DOCUMENT_MARKER', 'Маркер документа для уплаты в пенс. фонд' , 'STRING');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID, VALUE_ENTITY_ID) VALUES (23, 'GOV_PENSION_BANK_ACCOUNT_ID', 'Банковский счёт для уплаты в пенс. фонд' , 'REFERENCE' , 'BANK_ACCOUNT');
 INSERT INTO SYS_VARIABLE (ID, CODE, NAME, DATA_TYPE_ID, VALUE_ENTITY_ID) VALUES (24, 'GOV_PENSION_BANK_ACCOUNT_ID_<N>', 'Банковский счёт <N> для уплаты в пенс. фонд' , 'REFERENCE' , 'BANK_ACCOUNT');
 
 
