
INSERT INTO PROJECT_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1, 'NOTSTARTED', 'Not Started', 'Y', 'N', 'Y');
INSERT INTO PROJECT_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2, 'INPROGRESS', 'In Progress', 'N', 'N', 'Y');
INSERT INTO PROJECT_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (3, 'PLANE', 'Plane', 'N', 'N', 'Y');
INSERT INTO PROJECT_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (4, 'CANCELED', 'Canceled', 'N', 'Y', 'Y');
INSERT INTO PROJECT_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (5, 'COMPLETED', 'Closed', 'N', 'Y', 'Y');
