
INSERT INTO TASK_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (1, 'NOTSTARTED', 'Не начата', 'Y', 'N', 'Y');
INSERT INTO TASK_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (2, 'INPROGRESS', 'В процессе', 'N', 'N', 'Y');
INSERT INTO TASK_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (3, 'CANCELED', 'Отменена', 'N', 'Y', 'Y');
INSERT INTO TASK_STATUS (ID, CODE, NAME, IS_START, IS_FINISH, IS_SYSTEM) VALUES (4, 'COMPLETED', 'Выполнена', 'N', 'Y', 'Y');
