
INSERT INTO INDUSTRY (ID, NAME) VALUES (1, 'Communications');
INSERT INTO INDUSTRY (ID, NAME) VALUES (2, 'Finances');
INSERT INTO INDUSTRY (ID, NAME) VALUES (3, 'Automotive');
INSERT INTO INDUSTRY (ID, NAME) VALUES (4, 'IT');
INSERT INTO INDUSTRY (ID, NAME) VALUES (5, 'Accounting');
INSERT INTO INDUSTRY (ID, NAME) VALUES (6, 'Advertising');
INSERT INTO INDUSTRY (ID, NAME) VALUES (7, 'Agriculture');
INSERT INTO INDUSTRY (ID, NAME) VALUES (8, 'Construction');
INSERT INTO INDUSTRY (ID, NAME) VALUES (9, 'Distribution');
INSERT INTO INDUSTRY (ID, NAME) VALUES (10, 'Education');
INSERT INTO INDUSTRY (ID, NAME) VALUES (11, 'Healthcare');
INSERT INTO INDUSTRY (ID, NAME) VALUES (12, 'Insurance');
INSERT INTO INDUSTRY (ID, NAME) VALUES (13, 'Internet');
INSERT INTO INDUSTRY (ID, NAME) VALUES (14, 'Investments');
INSERT INTO INDUSTRY (ID, NAME) VALUES (15, 'Machine building');
INSERT INTO INDUSTRY (ID, NAME) VALUES (16, 'Pharmacy');
INSERT INTO INDUSTRY (ID, NAME) VALUES (17, 'Textil industry');