
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (1,'1','Client');
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (2,'2','Assistant');
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (3,'3','Supervisor');
