
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (1,'Без образования');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (2,'Дошкольное');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (3,'Начальное общее');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (4,'Основное общее');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (5,'Среднее общее');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (6,'Среднее профессиональное');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (7,'Начальное профессиональное');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (8,'Высшее профессиональное');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (9,'Послевузовское профессиональное');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (10,'Повышение квалификации');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (11,'Вторая специальность');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (12,'Магистр');
INSERT INTO EDUCATION_TYPE (ID, NAME) VALUES (13,'Бакалавр');
