
INSERT INTO PARTNER_TYPE (ID, NAME) VALUES (1, 'ёридическое лицо');
INSERT INTO PARTNER_TYPE (ID, NAME) VALUES (2, '‘изическое лицо');

ALTER TABLE PARTNER
 ADD PARTNER_TYPE_ID INTEGER DEFAULT 1 NOT NULL;

