
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (1, '1', 'Rank');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (2, '2', 'General');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (3, '3', 'Major-general');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (4, '4', 'Lieutenant-general');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (5, '5', 'Colonel-general');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (6, '6', 'Captain');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (7, '7', 'Major');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (8, '8', 'Lieutenant');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (9, '9', 'Corporal');
INSERT INTO MILITARY_RANK (ID, CODE, NAME) VALUES (10, '10', 'Colonel');
