
INSERT INTO VACATION_TYPE (ID, NAME) VALUES (1,'Type 1');
INSERT INTO VACATION_TYPE (ID, NAME) VALUES (2,'Type 2');
INSERT INTO VACATION_TYPE (ID, NAME) VALUES (3,'Type 3');
INSERT INTO VACATION_TYPE (ID, NAME) VALUES (4,'Type 4');

