
INSERT INTO MILITARY_STATUS (ID, CODE, NAME) VALUES (1,NULL,'Person liable for call-up');
INSERT INTO MILITARY_STATUS (ID, CODE, NAME) VALUES (2,NULL,'No Person liable for call-up');
INSERT INTO MILITARY_STATUS (ID, CODE, NAME) VALUES (3,NULL,'Military');
INSERT INTO MILITARY_STATUS (ID, CODE, NAME) VALUES (4,NULL,'Conscript');

