
INSERT INTO EDUCATION_FORM (ID, NAME) VALUES (1,'Очная');
INSERT INTO EDUCATION_FORM (ID, NAME) VALUES (2,'Очно-заочная (вечерняя)');
INSERT INTO EDUCATION_FORM (ID, NAME) VALUES (3,'Заочная');
INSERT INTO EDUCATION_FORM (ID, NAME) VALUES (4,'Экстернат');
