
/*===================================================*/
/*                                                   */
/* Update system                                     */
/*                                                   */
/*===================================================*/
/* 1. Rename entities
/*===================================================*/

 UPDATE SYSTEM_ENTITY SET ID = 'ASSET', CODE =  'ASSET' WHERE ID = 'FIXEDASSETS';
 UPDATE SYSTEM_ENTITY SET ID = 'PRODUCT_DETAIL_REGISTER', CODE =  'PRODUCT_DETAIL_REGISTER' WHERE ID = 'GOODS_DETAIL_REGISTER';
 UPDATE SYSTEM_ENTITY SET ID = 'PRODUCT_REGISTER', CODE = 'PRODUCT_REGISTER' WHERE ID = 'GOODS_REGISTER';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_DETAIL_REGISTER', CODE = 'M_PRODUCT_DETAIL_REGISTER' WHERE ID = 'M_GOODS_DETAIL_REGISTER';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_DETAIL_REGISTER_ID', CODE = 'M_PRODUCT_DETAIL_REGISTER_ID' WHERE ID = 'M_GOODS_DETAIL_REGISTER_ID';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_DETAIL_REGISTER_SUM', CODE = 'M_PRODUCT_DETAIL_REGISTER_SUM' WHERE ID = 'M_GOODS_DETAIL_REGISTER_SUM';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_REGISTER', CODE = 'M_PRODUCT_REGISTER' WHERE ID = 'M_GOODS_REGISTER';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_REGISTER_ID', CODE = 'M_PRODUCT_REGISTER_ID' WHERE ID = 'M_GOODS_REGISTER_ID';
 UPDATE SYSTEM_ENTITY SET ID = 'M_PRODUCT_REGISTER_SUM', CODE = 'M_PRODUCT_REGISTER_SUM' WHERE ID = 'M_GOODS_REGISTER_SUM';
 UPDATE SYSTEM_ENTITY SET ID = 'INTANGIBLE', CODE = 'INTANGIBLE' WHERE ID = 'NONMATERIAL';
 UPDATE SYSTEM_ENTITY SET ID = 'SECURE_OBJECT', CODE = 'SECURE_OBJECT' WHERE ID = 'SECURE_ENTITY';

/*===================================================*/
/* 2. Delete entities
/*===================================================*/

 DELETE FROM SYSTEM_ENTITY WHERE ID = 'LITTLEARTICLE';
 DELETE FROM SYSTEM_ENTITY WHERE ID = 'MATERIAL';

/*===================================================*/
/* 3. Insert entities
/*===================================================*/

 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('CONTACT_CONTEXT', 'CONTACT_CONTEXT', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('M_LEDGER_ACCOUNT_REGISTER', 'M_LEDGER_ACCOUNT_REGISTER', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('M_LEDGER_ACCOUNT_REGISTER_ID', 'M_LEDGER_ACCOUNT_REGISTER_ID', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('M_LEDGER_ACCOUNT_REGISTER_SUM', 'M_LEDGER_ACCOUNT_REGISTER_SUM', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PAYMENT_DOCUMENT_LINK', 'PAYMENT_DOCUMENT_LINK', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PAYMENT_MISSING', 'PAYMENT_MISSING', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PAYMENT_OUTCOME_TEMPLATE', 'PAYMENT_OUTCOME_TEMPLATE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PRODUCT_INSTANCE', 'PRODUCT_INSTANCE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('PROJECT_EMPLOYEE_LINK', 'PROJECT_EMPLOYEE_LINK', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_ATTR', 'SYSTEM_ATTR', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_ATTR_TYPE', 'SYSTEM_ATTR_TYPE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_ATTR_TYPE_GROUP', 'SYSTEM_ATTR_TYPE_GROUP', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_ENUMERATION', 'SYSTEM_ENUMERATION', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_PREFERENCE', 'SYSTEM_PREFERENCE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('SYSTEM_REFERENCE', 'SYSTEM_REFERENCE', '-', 'ENTITY');
 INSERT INTO SYSTEM_ENTITY (ID, CODE, NAME, ENTITY_TYPE_ID) VALUES ('TASK_EMPLOYEE_LINK', 'TASK_EMPLOYEE_LINK', '-', 'ENTITY');

