
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (43, 600, 1, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (44, 601, 2, 201, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (64, 600, 5, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (72, 600, 23, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (68, 601, 9, 201, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (66, 600, 8, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (56, 600, 4, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (69, 601, 6, 201, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (79, 600, 26, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (73, 600, 22, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (77, 600, 25, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (80, 600, 27, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (78, 601, 24, 201, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (59, 600, 7, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (83, 600, 29, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (82, 601, 28, 201, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (62, 600, 10, 200, NULL);
INSERT INTO WAREHOUSE_MOVE (ID, MTRL_RESPONSIBLE_ID, OWNER_ID, WAREHOUSE_ID, MOVE_TYPE) VALUES (63, 600, 11, 200, NULL);

