ALTER TABLE PARTNER DROP CONSTRAINT FK_PARTNER_PARTNER_TYPE;

ALTER TABLE EMPLOYEE_SICKLIST DROP CONSTRAINT FK_EMPLOYEE_SICKLIST_DOC;
ALTER TABLE EMPLOYEE_VACATION DROP CONSTRAINT FK_EMPLOYEE_VACATION_DOC;
ALTER TABLE EMPLOYEE_DISCHARGE DROP CONSTRAINT FK_EMPLOYEE_DISCHARGE_DOC;
ALTER TABLE EMPLOYEE_RECEPTION DROP CONSTRAINT FK_EMPLOYEE_RECEPTION_DOC;

ALTER TABLE CASH_OUTCOME DROP CONSTRAINT FK_CASH_OUTCOME_FIN_DOC;
ALTER TABLE CASH_INCOME DROP CONSTRAINT FK_CASH_INCOME_FIN_DOC;

ALTER TABLE PURCHASE_TAX_WAYBILL DROP CONSTRAINT FK_PURCHASE_TXWB_FIN_DOC;
ALTER TABLE PURCHASE_SERV DROP CONSTRAINT FK_PURCHASE_SERV_FIN_DOC;
ALTER TABLE PURCHASE_PLAN DROP CONSTRAINT FK_PURCHASE_PLAN_FIN_DOC;
ALTER TABLE PURCHASE_ORDER DROP CONSTRAINT FK_PURCHASE_ORDER_FIN_DOC;
ALTER TABLE PURCHASE_INVOICE DROP CONSTRAINT FK_PURCHASE_INV_FIN_DOC;

ALTER TABLE SALE_TAX_WAYBILL DROP CONSTRAINT FK_SALE_TXWB_FIN_DOC;
ALTER TABLE SALE_SERV DROP CONSTRAINT FK_SALE_SERV_FIN_DOC;
ALTER TABLE SALE_PLAN DROP CONSTRAINT FK_SALE_PLAN_FIN_DOC;
ALTER TABLE SALE_ORDER DROP CONSTRAINT FK_SALE_ORDER_FIN_DOC;
ALTER TABLE SALE_INVOICE DROP CONSTRAINT FK_SALE_INV_FIN_DOC;

ALTER TABLE PAYMENT_OUTCOME DROP CONSTRAINT FK_PAYMENT_OUTCOME_FIN_DOC;
ALTER TABLE PAYMENT_INCOME DROP CONSTRAINT FK_PAYMENT_INCOME_FIN_DOC;

ALTER TABLE GOODS_OUTCOME DROP CONSTRAINT FK_GOODS_OUTCOME_FIN_DOC;
ALTER TABLE GOODS_INCOME DROP CONSTRAINT FK_GOODS_INCOME_FIN_DOC;

ALTER TABLE INVENTORY_OUTCOME DROP CONSTRAINT FK_INVENTORY_OUTCOME_FIN_DOC;
ALTER TABLE INVENTORY_INCOME DROP CONSTRAINT FK_INVENTORY_INCOME_FIN_DOC;
ALTER TABLE INVENTORY_WRITEOFF DROP CONSTRAINT FK_INVENTORY_WRITEOFF_FIN_DOC;
ALTER TABLE INVENTORY_MOVE DROP CONSTRAINT FK_INVENTORY_MOVE_FIN_DOC;
ALTER TABLE INVENTORY_REST DROP CONSTRAINT FK_INVENTORY_REST_FIN_DOC;

ALTER TABLE CONTRACT DROP CONSTRAINT FK_CONTRACT_FIN_DOC;
ALTER TABLE FINANCE_DOCUMENT DROP CONSTRAINT FK_DOCUMENT_FIN_DOCUMENT;

ALTER TABLE GOODS DROP CONSTRAINT FK_GOODS_PRODUCT;

DROP INDEX FIN_DOC_TYPE_MOVE;
DROP INDEX DOC_TYPE_CATEGORY;
DROP INDEX DOC_TYPE_SECTION;

DROP INDEX USER_ORG_UNIQUE;
DROP INDEX ROLE_INTERFACE_UNIQUE;
DROP INDEX USER_ROLE_UNIQUE;

DROP INDEX SYS_ENTITY_CODE;
DROP INDEX BUSINESSABLE_ENTITY_ID;

DROP INDEX CONTACTABLE_OWNER;
DROP INDEX BUSINESSABLE_OWNER;
