

INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (1, 1, NULL, '1000', 'Goods');
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (2, 1, NULL, '2000', 'Service');



INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (1,'Type 1');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (2,'Type 2');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (3,'Type 3');

INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (1,'With VAT');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (2,'Only VAT');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (3,'Only amount');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (4,'Without amount and VAT');

