
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (1,'1','Клиент');
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (2,'2','Консультант');
INSERT INTO TASK_ROLE (ID, CODE, NAME) VALUES (3,'3','Исполнитель');
