
INSERT INTO DISCHARGE_TYPE (ID, CODE, NAME) VALUES (1, NULL, 'Type 1');
INSERT INTO DISCHARGE_TYPE (ID, CODE, NAME) VALUES (2, NULL, 'Type 2');
INSERT INTO DISCHARGE_TYPE (ID, CODE, NAME) VALUES (3, NULL, 'Type 3');
INSERT INTO DISCHARGE_TYPE (ID, CODE, NAME) VALUES (4, NULL, 'Type 4');
