
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (1, 'LOW', 'Низкий', 1, 'Y');
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (2, 'NORMAL', 'Нормальный', 2, 'Y');
INSERT INTO TASK_PRIORITY (ID, CODE, NAME, ORDER_NUMBER, IS_SYSTEM) VALUES (3, 'HIGH', 'Высокий', 3, 'Y');
