

INSERT INTO PAYMENT_OUTCOME (ID, PARTNER_BANK_ACCOUNT_ID, ORGANIZATION_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (34, 6, 1, 1, 1, '2011-01-15', 'за товар', NULL);
INSERT INTO PAYMENT_OUTCOME (ID, PARTNER_BANK_ACCOUNT_ID, ORGANIZATION_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (35, 6, 1, 1, 1, '2011-02-08', 'за товар', NULL);
INSERT INTO PAYMENT_OUTCOME (ID, PARTNER_BANK_ACCOUNT_ID, ORGANIZATION_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (36, 7, 1, 1, 1, '2011-02-10', 'за ноутбуки', NULL);
INSERT INTO PAYMENT_OUTCOME (ID, PARTNER_BANK_ACCOUNT_ID, ORGANIZATION_BANK_ACCOUNT_ID, TAXPRINT_TYPE_ID, PAYMENT_TYPE_ID, PAYMENT_DATE, PAYMENT_MISSING, BANK_REFERENCE_CODE) VALUES (37, 6, 1, 1, 1, '2011-03-15', 'за товар', NULL);


