
/*==============================================================*/
/* Oracle                                                       */
/* http://www.oracle.com                                        */
/*==============================================================*/

INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (1, 191, 'Московская');
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (2, 229, 'Киевская');
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (3, 229, 'Харьковская');
INSERT INTO REGION (ID, COUNTRY_ID, NAME) VALUES (4, 36, 'Минская');



INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (1, 'Москва', 1, 191);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (2, 'Санкт-Петербург', 1, 191);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (3, 'Самара', 1, 191);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (4, 'Тюмень', 1, 191);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (5, 'Киев', 1, 229);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (6, 'Харьков', 1, 229);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (7, 'Днепропетровск', 1, 229);
INSERT INTO LOCALITY (ID, NAME, LOCALITY_TYPE_ID, COUNTRY_ID) VALUES (8, 'Минск', 1, 36);

INSERT INTO CITY (ID) VALUES (1);
INSERT INTO CITY (ID) VALUES (2);
INSERT INTO CITY (ID) VALUES (3);
INSERT INTO CITY (ID) VALUES (4);
INSERT INTO CITY (ID) VALUES (5);
INSERT INTO CITY (ID) VALUES (6);
INSERT INTO CITY (ID) VALUES (7);
INSERT INTO CITY (ID) VALUES (8);


INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (1, 1, NULL, '1000', 'Товар');
INSERT INTO PRODUCT_GROUP (ID, PRODUCT_SECTION_ID, PARENT_ID, CODE, NAME) VALUES (2, 1, NULL, '2000', 'Услуги');



INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (1,'Электронно');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (2,'Почтой');
INSERT INTO PAYMENT_TYPE (ID, NAME) VALUES (3,'Телеграфом');

INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (1,'Указывать в тексте сумму и НДС');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (2,'Указывать в тексте только НДС');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (3,'Указывать в тексте только сумму');
INSERT INTO TAXPRINT_TYPE (ID, NAME) VALUES (4,'не указывать в тексте сумму и НДС');

