
INSERT INTO PIM_APPOINTMENT_PRIORITY (ID, CODE, NAME, IS_SYSTEM) VALUES (1, 'LOW', 'Низкий', 'Y');
INSERT INTO PIM_APPOINTMENT_PRIORITY (ID, CODE, NAME, IS_SYSTEM) VALUES (2, 'NORMAL', 'Нормальный', 'Y');
INSERT INTO PIM_APPOINTMENT_PRIORITY (ID, CODE, NAME, IS_SYSTEM) VALUES (3, 'HIGH', 'Высокий', 'Y');
