
/* DEPRECATED. DON'T REMOVE */

INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (1,  '01', 'MD-Плееры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (2,  '02', 'СD-Плееры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (3,  '03', 'MP3-плееры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (4,  '04', 'Video/DVD-плееры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (5,  '05', 'Диктофоны');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (6,  '06', 'Синтезаторы');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (7,  '07', 'Видеокамеры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (8,  '08', 'Фотокамеры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (9,  '09', 'Портативные телевизоры');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (10, '10', 'Радиотелефоны');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (11, '11', 'Сотовые трубки');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (12, '12', 'Карманные ПК');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (13, '13', 'Ноутбуки');
INSERT INTO PRODUCT_CLASS_GROUP (ID, CODE, NAME) VALUES (14, '14', 'Переводчики');
