
INSERT INTO PAYROLL_MODE (ID, NAME) VALUES (1,'Inconstant');
INSERT INTO PAYROLL_MODE (ID, NAME) VALUES (2,'Constant for one');
INSERT INTO PAYROLL_MODE (ID, NAME) VALUES (3,'Constant for all');
